### PR TITLE
Updated mod to minecraft 1.11.2

### PR DESCRIPTION
**Pull request by Lothrazar**

### CODE REVIEW

**Comment by Vorquel** [comment]
Thanks for your contribution. I'm no longer interested in minecraft modding. If you want, you can post this update yourself on curseforge or wherever. If anyone asks, you can reference this comment as proof of permission.

**Comment by Lothrazar** [comment]
@Vorquel cool thanks so much dude!

**Comment by Lothrazar** [comment]
Hey, if you still have access to your curse login, and if its not too much trouble, could you use the 'transfer ownership feature for the curse project ( https://mods.curse.com/mc-mods/minecraft/233659-similsax-transtructors )

You just go to settings -> members and then Transfer Ownership is on the right.  I will leave you on the list as original author of course.

My username is "lothrazar" https://mods.curse.com/members/lothrazar

Please and thank you.

If not then don't worry about it, i can make a second project and link back to the original.

**Comment by Vorquel** [comment]
Transfer done. Have fun.

**Comment by Vorquel** [comment]
Oh, as a sidenote, you can keep all the points generated by the mod from now on.

**Comment by Lothrazar** [comment]
thanks so much <3 <3 you are awesome

**Pull request closed without merging**
